### PR TITLE
single threaded work queue

### PR DESCRIPTION
**Pull request by drossetti**
introduce single-threaded work queue
based on std c++ library
requires C++0x/11 features

### CODE REVIEW

**Comment by drossetti** [comment]
@e-ago this tree is based on nor, so please pull that one 1st

**Comment by drossetti** [comment]
on P9, when:
- enabling WAIT_NOR
- disabling REMOTE_FLUSH
- using the checker, I can see that the GPU has successfully waited on the last submitted wait operation.
despite that, the CUDA stream is empty on at least one rank.

```
[62287] GDS DBG  gds_post_ops() n_ops=2
[62287] GDS DBG  gds_post_ops() op[0] type:0000000d
[62287] GDS DBG  gds_post_ops() OP_WAIT_DWORD dev_ptr=7fff9b7cf3fc data=feffffff type=d
[62287] GDS DBG  gds_fill_poll() op=1 addr=0x7fff9b7cf3fc value=feffffff cond=CU_STREAM_WAIT_VALUE_NOR flags=00000003
[62287] GDS DBG  pre() 1999 injecting pre poke
[62287] GDS DBG  gds_fill_poke() addr=0x2fc4b0a0 value=00000001 flags=00000002
[62287] GDS DBG  gds_map_mem() ptr=0x2fc4b0a0 size=4 mem_type=00000002
[62287] GDS DBG  gds_fill_poke() op=2 addr=0x2fc4b0a0 value=00000001 flags=00000001
[62287] GDS DBG  post() 1999 injecting post poke
[62287] GDS DBG  gds_fill_poke() addr=0x2fc4b0a0 value=00000002 flags=00000002
[62287] GDS DBG  gds_map_mem() ptr=0x2fc4b0a0 size=4 mem_type=00000002
[62287] GDS DBG  gds_fill_poke() op=2 addr=0x2fc4b0a0 value=00000002 flags=00000001
[62287] GDS DBG  gds_post_ops() op[1] type:00000004
[62287] GDS DBG  gds_post_ops() OP_STORE_DWORD dev_ptr=7fff9b7a0138 data=0
[62287] GDS DBG  gds_fill_poke() op=2 addr=0x7fff9b7a0138 value=00000000 flags=00000001
[62287] GDS ERR   run() 1999 signaled NOR addr=0x7fff9b7cf3fc still not observed by GPU
[62287] GDS DBG  gds_enable_weak_consistency() gds_disable_weak_consistency=0
[62287] GDS DBG  gds_stream_batch_ops() nops=4 flags=00000000
[62287] GDS ERR   run() 1999 signaled NOR addr=0x7fff9b7cf3fc still not observed by GPU
[62287] GDS ERR   run() 1999 signaled NOR addr=0x7fff9b7cf3fc still not observed by GPU
DBG:  [gpu_post_release_tracking_event] recording 1 tracking event 0x2fb71f40
[62287] GDS DBG  run() GPU is all set, dequeing 1999
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
ERR:  [main] [0] iter:48 unexpected rx ev 0, batch len 20
....
ERR:  [main] [0] iter:49 unexpected rx ev 0, batch len 20
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
ERR:  [main] [0] iter:50 unexpected rx ev 0, batch len 20
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
...
```

**Comment by e-ago** [comment]
The same on DGX-1V:
```[62714] GDS ERR   run() 1999 signaled NOR addr=0x7f92674fa9fc still not observed by GPU
[62714] GDS ERR   run() 1998 signaled NOR addr=0x7f926751f9fc still not observed by GPU
[62714] GDS ERR   run() 1999 signaled NOR addr=0x7f92674fa9fc still not observed by GPU
[62714] GDS ERR   run() 1998 signaled NOR addr=0x7f926751f9fc still not observed by GPU
[62714] GDS ERR   run() 1999 signaled NOR addr=0x7f92674fa9fc still not observed by GPU
[62714] GDS ERR   run() 1998 signaled NOR addr=0x7f926751f9fc still not observed by GPU
[62714] GDS ERR   run() 1999 signaled NOR addr=0x7f92674fa9fc still not observed by GPU
[62714] GDS ERR   run() 1998 signaled NOR addr=0x7f926751f9fc still not observed by GPU
[62714] GDS ERR   run() 1999 signaled NOR addr=0x7f92674fa9fc still not observed by GPU
[62714] GDS ERR   run() 1998 signaled NOR addr=0x7f926751f9fc still not observed by GPU
[62714] GDS ERR   run() 1999 signaled NOR addr=0x7f92674fa9fc still not observed by GPU
[62714] GDS DBG   run() GPU is all set, dequeing 1998
DBG:  [poll_recv_cq] got recv event
ERR:  [main] [0] iter:27258 unexpected tx ev 0, batch len 20
ERR:  [main] [0] iter:27258 unexpected rx ev 1, batch len 20
[62714] GDS DBG   run() GPU is all set, dequeing 1999
DBG:  [gpu_post_release_tracking_event] recording 1 tracking event 0x4063af0
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event
DBG:  [poll_send_cq] got send event```

**Comment by e-ago** [comment]
Although the worker is an useful object to track CUDA stream operations, the problem with NOR in `gds_kernel_latency` occurs also when using the CPU (options `-P -U`) and the CUDA stream is never used for communications.

**Comment by drossetti** [comment]
indeed the problem was related to libmlx5

**Comment by e-ago** [comment]
Tested and approved

**Pull request merged**
