### PR TITLE
enable Volta features when available

### LINKED ISSUE #35: add support for Volta class features
Volta class GPUs support:
- 64bits VALUE_WRITE
- WAIT_VALUE_NOR

### PR DESCRIPTION
**Pull request by drossetti**
- merge peer attributes into peer object
- enable use of write64 and wait_nor

notes:
- still need to test on Volta
- branch will be rebased from master once the other pull request will be merged

fixes #35

### CODE REVIEW

**Comment by drossetti** [comment]
tested on ivy2/3 with r396.21, cuda 9.2.99, K40m

**Comment by drossetti** [comment]
I can see a perf degradation, from 8.0 to 8.3usec/iter
```
./gds_kernel_loopback_latency.sh
libgdsync build version 0x00020001, major=2 minor=1
libgdsync queried version 0x00020001
INFO: use_gpumem=1
INFO: gpu id=0
INFO: max_batch_len=20
[0] pid=1620 server:localhost
[0] requested IB device: <mlx5_0>
use gpumem: 1
initializing CUDA
There are 1 devices supporting CUDA, picking N.0
GPU id:0 dev:0 name:Tesla K40m pci 2:0
creating CUDA Primary Ctx on device:0 id:0
making it the current CUDA Ctx
num SMs per GPU:15
clock rate:875500
created main test CUDA stream 0x19011f0
created stream server CUDA stream 0x1ad8c30
created stream cliebt CUDA stream 0x1ad8df0
created 0 tracking event 0x1b693f0
created 1 tracking event 0x1b69550
created 2 tracking event 0x1b696b0
created 3 tracking event 0x1b69810
allocating GPU memory buf
cuMemAlloc() of a 12288 bytes GPU buffer
allocated GPU buffer address at 00000023045c0000
ctx buf=0x23045c0000
poisoning GPU buffer, filled with '0x00' !!!
[1620] GDS WARN  support_memops() flag=1
  local address:  LID 0x000c, QPN 0x0000a6, PSN 0x2b9ede: GID ::
000c:0000a6:2b9ede:
000c:0000a6:2b9ede
  remote address: LID 0x000c, QPN 0x0000a6, PSN 0x2b9ede, GID ::
[1620] GDS WARN  gds_fill_poll() RDMA consistency for pre-launched GPU work is not guaranteed at the moment
[0] batch 0: posted 20 sequences
[0] batch 1: posted 20 sequences
[0] batch 2: posted 20 sequences
pre-posting took 558.00 usec

batch info: rx+kernel+tx 20 per batch
pre-posted 60 sequences in 2 batches
GPU kernel calc buf size: 0
iters=1000 tx/rx_depth=1024

testing....
[0] 256000 bytes in 0.01 seconds = 244.71 Mbit/sec
[0] 1000 iters in 0.01 seconds = 8.37 usec/iter

```

**Comment by e-ago** [comment]
Tested on DGX-1V lab18 with Tesla V100 and CUDA 9.2, r396.14, `gds_kernel_latency` test:
```
[1] batch 0: posted 20 sequences
[0] batch 0: posted 20 sequences
[1] batch 1: posted 20 sequences
[0] batch 1: posted 20 sequences
[1] batch 2: posted 20 sequences
pre-posting took 4229.00 usec
[0] batch 2: posted 20 sequences
pre-posting took 4301.00 usec

batch info: rx+kernel+tx 20 per batch
pre-posted 60 sequences in 2 batches
GPU kernel calc buf size: 131072
iters=1000 tx/rx_depth=1024

testing....
[7] unexpected rx ev 15, batch len 20
[8] unexpected rx ev 19, batch len 20
[9] unexpected rx ev 16, batch len 20
[9] unexpected tx ev 19, batch len 20
[10] unexpected rx ev 16, batch len 20
[14] unexpected rx ev 19, batch len 20
[16] unexpected rx ev 19, batch len 20
[16] unexpected tx ev 19, batch len 20
[17] unexpected rx ev 19, batch len 20
[18] unexpected rx ev 19, batch len 20
[21] unexpected tx ev 19, batch len 20
[22] unexpected tx ev 19, batch len 20
[24] unexpected rx ev 19, batch len 20
[27] unexpected rx ev 19, batch len 20
[32] unexpected rx ev 19, batch len 20
[35] unexpected rx ev 19, batch len 20
[36] unexpected rx ev 19, batch len 20
[38] unexpected rx ev 19, batch len 20
[39] unexpected rx ev 19, batch len 20
[41] unexpected rx ev 16, batch len 20
[48] unexpected rx ev 19, batch len 20
[49] unexpected rx ev 19, batch len 20
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
[51] unexpected tx ev 1, batch len 20
[51] unexpected rx ev 1, batch len 20
[53] unexpected tx ev 0, batch len 20
[53] unexpected rx ev 1, batch len 20
[58] unexpected tx ev 0, batch len 20
[58] unexpected rx ev 1, batch len 20
[66] unexpected tx ev 0, batch len 20
[66] unexpected rx ev 1, batch len 20
[74] unexpected tx ev 0, batch len 20
[74] unexpected rx ev 1, batch len 20
[77] unexpected tx ev 0, batch len 20
[77] unexpected rx ev 1, batch len 20
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
[86] unexpected tx ev 0, batch len 20
[86] unexpected rx ev 1, batch len 20
[88] unexpected tx ev 0, batch len 20
[88] unexpected rx ev 1, batch len 20
[90] unexpected tx ev 0, batch len 20
[90] unexpected rx ev 1, batch len 20
[95] unexpected tx ev 0, batch len 20
[95] unexpected rx ev 1, batch len 20
[99] unexpected tx ev 0, batch len 20
[99] unexpected rx ev 1, batch len 20
[102] unexpected tx ev 0, batch len 20
[102] unexpected rx ev 1, batch len 20
[104] unexpected tx ev 0, batch len 20
[104] unexpected rx ev 1, batch len 20
[108] unexpected tx ev 0, batch len 20
[108] unexpected rx ev 1, batch len 20
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
[112] unexpected tx ev 0, batch len 20
[112] unexpected rx ev 1, batch len 20
[123] unexpected tx ev 0, batch len 20
[123] unexpected rx ev 1, batch len 20
[127] unexpected tx ev 0, batch len 20
[127] unexpected rx ev 1, batch len 20
[129] unexpected tx ev 0, batch len 20
[129] unexpected rx ev 1, batch len 20
[139] unexpected tx ev 0, batch len 20
[139] unexpected rx ev 1, batch len 20
[142] unexpected tx ev 0, batch len 20
[142] unexpected rx ev 1, batch len 20
[143] unexpected tx ev 0, batch len 20
[143] unexpected rx ev 1, batch len 20
[147] unexpected tx ev 0, batch len 20
[147] unexpected rx ev 1, batch len 20
[152] unexpected tx ev 0, batch len 20
[152] unexpected rx ev 1, batch len 20
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
[158] unexpected tx ev 0, batch len 20
[158] unexpected rx ev 1, batch len 20
[163] unexpected tx ev 0, batch len 20
[163] unexpected rx ev 1, batch len 20
[165] unexpected tx ev 0, batch len 20
[165] unexpected rx ev 1, batch len 20
[167] unexpected tx ev 0, batch len 20
[167] unexpected rx ev 1, batch len 20
[51] unexpected tx ev 3, batch len 20
[51] unexpected rx ev 0, batch len 20
[170] unexpected tx ev 0, batch len 20
[170] unexpected rx ev 1, batch len 20
[177] unexpected tx ev 0, batch len 20
[177] unexpected rx ev 1, batch len 20
[181] unexpected tx ev 0, batch len 20
[181] unexpected rx ev 1, batch len 20
[184] unexpected tx ev 0, batch len 20
[184] unexpected rx ev 1, batch len 20
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
gpu_wait_tracking_event nothing to do (12)
[1] 2048000 bytes in 0.02 seconds = 1059.70 Mbit/sec
[1] 1000 iters in 0.02 seconds = 15.46 usec/iter
gpu_wait_tracking_event nothing to do (12)
[0] 2048000 bytes in 0.02 seconds = 1061.41 Mbit/sec
[0] 1000 iters in 0.02 seconds = 15.44 usec/iter
```

Original perf: 
```
[1] 2048000 bytes in 0.04 seconds = 435.28 Mbit/sec
[1] 1000 iters in 0.04 seconds = 37.64 usec/iter
[0] 2048000 bytes in 0.04 seconds = 435.70 Mbit/sec
[0] 1000 iters in 0.04 seconds = 37.60 usec/iter
```

**Comment by e-ago** [comment]
Tested on DGX-1V lab18 with Tesla V100 and CUDA 9.2, r396.14, without `volta_features`:

[0] 256000 bytes in 0.02 seconds = 112.56 Mbit/sec
[0] 1000 iters in 0.02 seconds = 18.19 usec/iter
```

Tested on DGX-1V lab18 with Tesla V100 and CUDA 9.2, r396.14, with `volta_features`:
```
[0] 256000 bytes in 0.02 seconds = 123.17 Mbit/sec
[0] 1000 iters in 0.02 seconds = 16.63 usec/iter
```

**Comment by e-ago** [comment]
Your `gds_kernel_loopback_latency.sh` on brdw0 with Tesla P100 and CUDA 9.0, r396.14, without `volta_features`:
```
[0] 256000 bytes in 0.01 seconds = 155.66 Mbit/sec
[0] 1000 iters in 0.01 seconds = 13.16 usec/iter
```

Your `gds_kernel_loopback_latency.sh` on brdw0 with Tesla P100 and CUDA 9.0, r396.14, with `volta_features`:
```
[0] 256000 bytes in 0.01 seconds = 151.00 Mbit/sec
[0] 1000 iters in 0.01 seconds = 13.56 usec/iter
```

**Comment by drossetti** [comment]
branch just rebased from master

**Comment by e-ago** [comment]
Tested on P9 and DGX-1V with gds_kernel_loopback_latency and hpgmg (SA and KI models)

**Pull request merged**
