### PR TITLE
implement !peersync case in gds_kernel_loopback_latency via CUDA stream callbacks

### PR DESCRIPTION
**Pull request by drossetti**
These changes help evaluating the relative performance of the direct Async (GPU->NIC) vs offloaded (GPU->CPU->NIC) path.

### CODE REVIEW

**Comment by e-ago** [comment]
Testing on ivys2/3, with CUDA 9.1, r396.21 `gds_kernel_latency -P -U` (without peersync and using descriptors) gets stuck:

```
INFO: switching PeerSync OFF
INFO: use_desc_apis=1
[0] pid=15998 client:drossetti-ivy3.nvidia.com
[0] picking 1st available device
USE_GPU=0(0)
[1] pid=23278 server:drossetti-ivy2.nvidia.com
[1] picking 1st available device
USE_GPU=0(0)
GPU_ENABLE_DEBUG=0
GPU_ENABLE_DEBUG=0
[1]  local address:  LID 0x0003, QPN 0x000753, PSN 0x10101b: GID
[0]  local address:  LID 0x000c, QPN 0x000759, PSN 0x734733: GID
[0] remote address: LID 0x0003, QPN 0x000753, PSN 0x10101b, GID ::
[1] remote address: LID 0x000c, QPN 0x000759, PSN 0x734733, GID ::

pre-posted 0 sequences in 2 batches
GPU kernel calc buf size: 131072
iters=1000 tx/rx_depth=1024

testing....
```

**Comment by drossetti** [comment]
@e-ago I only modified gds_kernel_loopback_latency. 
So this regression should be preexisting.
Can you verify that gds_kernel_loopback_latency works in the other branches? the sequence is:
master, new_memops, nvtx (not worth the pain), streamcb

**Comment by drossetti** [comment]
just verified that gds_kernel_loopback_latency works on each individual machine

drossetti@drossetti-ivy2 15:59 (117) libgdsync>./gds_kernel_loopback_latency.sh
libgdsync build version 0x00020002, major=2 minor=2
libgdsync queried version 0x00020002
INFO: use_gpumem=1
INFO: gpu id=0
INFO: kernel calc size=8388608
INFO: message size=4096
INFO: max_batch_len=20
INFO: use_desc_apis=1
[0] pid=22932 server:localhost
[0] requested IB device: <mlx5_0>
use gpumem: 1
GPU_ENABLE_DEBUG=0
INFO: [gpu_init] GPU id:0 dev:0 name:Tesla K40m pci 2:0
INFO: [gpu_init] creating CUDA Primary Ctx on device:0 id:0
allocating GPU memory buf
ctx buf=0x23045c0000
  local address:  LID 0x000c, QPN 0x00075b, PSN 0x2aed42: GID ::
000c:00075b:2aed42:
000c:00075b:2aed42
  remote address: LID 0x000c, QPN 0x00075b, PSN 0x2aed42, GID ::
[22932] GDS WARN  gds_fill_poll() RDMA consistency for pre-launched GPU work is not guaranteed at the moment
[0] batch 0: posted 20 sequences
[0] batch 1: posted 20 sequences
[0] batch 2: posted 20 sequences
pre-posting took 712.00 usec

batch info: rx+kernel+tx 20 per batch
pre-posted 60 sequences in 2 batches
GPU kernel calc buf size: 8388608
iters=5000 tx/rx_depth=1024

testing....
[0] 40960000 bytes in 2.55 seconds = 128.73 Mbit/sec
[0] 5000 iters in 2.55 seconds = 509.08 usec/iter


drossetti@drossetti-ivy3 16:00 (71) libgdsync>./gds_kernel_loopback_latency.sh
libgdsync build version 0x00020002, major=2 minor=2
libgdsync queried version 0x00020002
INFO: use_gpumem=1
INFO: gpu id=0
INFO: kernel calc size=8388608
INFO: message size=4096
INFO: max_batch_len=20
INFO: use_desc_apis=1
[0] pid=24586 server:localhost
[0] requested IB device: <mlx5_0>
use gpumem: 1
GPU_ENABLE_DEBUG=0
INFO: [gpu_init] GPU id:0 dev:0 name:Tesla K40m pci 2:0
INFO: [gpu_init] creating CUDA Primary Ctx on device:0 id:0
allocating GPU memory buf
ctx buf=0x23045c0000
  local address:  LID 0x0003, QPN 0x000755, PSN 0x6dda97: GID ::
0003:000755:6dda97:
0003:000755:6dda97
  remote address: LID 0x0003, QPN 0x000755, PSN 0x6dda97, GID ::
[24586] GDS WARN  gds_fill_poll() RDMA consistency for pre-launched GPU work is not guaranteed at the moment
[0] batch 0: posted 20 sequences
[0] batch 1: posted 20 sequences
[0] batch 2: posted 20 sequences
pre-posting took 693.00 usec

batch info: rx+kernel+tx 20 per batch
pre-posted 60 sequences in 2 batches
GPU kernel calc buf size: 8388608
iters=5000 tx/rx_depth=1024

testing....
[0] 40960000 bytes in 2.54 seconds = 129.00 Mbit/sec
[0] 5000 iters in 2.54 seconds = 508.03 usec/iter

**Comment by drossetti** [comment]
also in !peersync (-P) mode


drossetti@drossetti-ivy2 15:59 (118) libgdsync>./gds_kernel_loopback_latency.sh
libgdsync build version 0x00020002, major=2 minor=2
libgdsync queried version 0x00020002
INFO: use_gpumem=1
INFO: gpu id=0
INFO: kernel calc size=8388608
INFO: message size=4096
INFO: max_batch_len=20
INFO: use_desc_apis=1
INFO: switching PeerSync OFF
WARNING: PeerSync OFF is approximated using CUDA stream callbacks
[0] pid=22954 server:localhost
[0] requested IB device: <mlx5_0>
use gpumem: 1
GPU_ENABLE_DEBUG=0
INFO: [gpu_init] GPU id:0 dev:0 name:Tesla K40m pci 2:0
INFO: [gpu_init] creating CUDA Primary Ctx on device:0 id:0
allocating GPU memory buf
ctx buf=0x23045c0000
  local address:  LID 0x000c, QPN 0x00075c, PSN 0x8ad90a: GID ::
000c:00075c:8ad90a:
000c:00075c:8ad90a
  remote address: LID 0x000c, QPN 0x00075c, PSN 0x8ad90a, GID ::
[0] batch 0: posted 20 sequences
[0] batch 1: posted 20 sequences
[0] batch 2: posted 20 sequences
pre-posting took 1054.00 usec

batch info: rx+kernel+tx 20 per batch
pre-posted 60 sequences in 2 batches
GPU kernel calc buf size: 8388608
iters=5000 tx/rx_depth=1024
testing....
[0] 40960000 bytes in 5.00 seconds = 65.54 Mbit/sec
[0] 5000 iters in 5.00 seconds = 999.96 usec/iter


drossetti@drossetti-ivy3 16:00 (72) libgdsync>./gds_kernel_loopback_latency.sh
libgdsync build version 0x00020002, major=2 minor=2
libgdsync queried version 0x00020002
INFO: use_gpumem=1
INFO: gpu id=0
INFO: kernel calc size=8388608
INFO: message size=4096
INFO: max_batch_len=20
INFO: use_desc_apis=1
INFO: switching PeerSync OFF
WARNING: PeerSync OFF is approximated using CUDA stream callbacks
[0] pid=24607 server:localhost
[0] requested IB device: <mlx5_0>
use gpumem: 1
GPU_ENABLE_DEBUG=0
INFO: [gpu_init] GPU id:0 dev:0 name:Tesla K40m pci 2:0
INFO: [gpu_init] creating CUDA Primary Ctx on device:0 id:0
allocating GPU memory buf
ctx buf=0x23045c0000
  local address:  LID 0x0003, QPN 0x000756, PSN 0xf150fd: GID ::
0003:000756:f150fd:
0003:000756:f150fd
  remote address: LID 0x0003, QPN 0x000756, PSN 0xf150fd, GID ::
[0] batch 0: posted 20 sequences
[0] batch 1: posted 20 sequences
[0] batch 2: posted 20 sequences
pre-posting took 1118.00 usec
batch info: rx+kernel+tx 20 per batch
pre-posted 60 sequences in 2 batches
GPU kernel calc buf size: 8388608
iters=5000 tx/rx_depth=1024
testing....
[0] 40960000 bytes in 5.00 seconds = 65.54 Mbit/sec
[0] 5000 iters in 5.00 seconds = 999.87 usec/iter

**Comment by drossetti** [comment]
running gds_kernel_latency works in !peersync mode over the following branches:
* streamcb: FAIL
* new_memops: FAIL
* master: OK

FAIL=stuck after pre-submisison, task show user-mode process taking 100% of CPU core

**Comment by drossetti** [comment]
bisecting:
fails at `bbaf2e2        don't use extended memops by default (Davide Rossetti)`
fails at `186b2b4        fix merge breakages (Davide Rossetti)`
does not build at `9e1731a cleanups, passing on K40m (Davide Rossetti)`
does not build at `9a36de6 translate CUDA_ERROR_NOT_SUPPORTED, propagate error ...`
does not build at `b95132 introduce GDSCHECK (Davide Rossetti)`

**Comment by drossetti** [comment]
rewriting new_memops branch to fix the compile breakages earlier

**Comment by drossetti** [comment]
bisected the !peersync problem, it is due to:
`e94c87a        (HEAD) use gpu debug/error/tracing functions. refactor code to support non-peersync mode (still not working)`
it seems like !peersync case was never supposed to work

**Comment by drossetti** [comment]
filed #63 to track future work

**Comment by drossetti** [comment]
@e-ago you should use gds_kernel_loopback_latency to test the feature added by this PR

**Comment by e-ago** [comment]
Tested again on ivys, I can confirm that:
- gds_kernel_loopback_latency, peersync OK, !peersync OK
- gds_kernel_latency, peersync OK, !peersync FAIL ( #64  )
- gds_sanity and gds_poll_lat, FAIL ( #60 )

On the master branch, gds_kernel_latency passes all tests.

**Comment by drossetti** [comment]
>> On the master branch, gds_kernel_latency passes all tests.

that is because on gds_kernel_latency really !peersync was basically a no-op.

**Pull request merged**
